---
- name: "Setup and Configure Module 1"
  vars_files:
    - values.yml
- hosts: localhost
  tasks: 
  - name: "Generate registration command"
  # note that this module isn't in the Execution Environment and needs to be added.
    redhat.satellite.registration_command:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      validate_certs: false
      smart_proxy: "capsule.{{ subdomain }}"
      setup_remote_execution: true
      organization: "Default Organization"
      activation_keys: "client_key"
      insecure: true
      lifecycle_environment: "Development"        
    register: command
      
- hosts: nodes
  tasks:
  - name: "Register the hosts to the capsule"
    ansible.builtin.shell:
      cmd: "{{ command.registration_command }}"