---
- name: "Setup Module 3"
  hosts: localhost
  vars_files:
    - /tmp/vars.yml
  tasks:
  - name: "Remove the Directory Server Repo to create Orphans"
    redhat.satellite.repository:
      username: "{{ var_workshop_satellite_user_name }}"
      password: "{{ var_workshop_satellite_user_password }}"
      server_url: "https://{{ var_workshop_satellite_url }}"
      name: "Red Hat Directory Server 12 for RHEL 9 x86_64 RPMs 9"
      state: absent
      content_type: "yum"
      product: "Red Hat Directory Server"
      organization: "Default Organization"
      url: "https://cdn.redhat.com/content/dist/rhel9/9/x86_64/resilientstorage/os"
      download_policy: immediate

#Ensure that the Satellite has a automatic cleanup disabled.
- name: "Run satellite-installer"
  hosts: "satellite.{{ var_subdomain_internal }}"
  become: True
  vars_files:
    - /tmp/vars.yml
  tasks:
  - name: Satellite automatic cleanup tasks are disabled.
    ansible.builtin.shell: "satellite-installer --foreman-plugin-tasks-automatic-cleanup false"

  - name: Set orphan content protection time
    ansible.builtin.shell: "hammer settings set --name orphan_protection_time --value 3"
