---                                                                                                    
- name: "Break Registration on Node 2"                                                                 
  vars_files:                                                                                          
    - /tmp/vars.yml                                                                                    
  hosts: "node2.{{ var_subdomain_internal }}"
  become: true                                                        
  tasks: 
    - name: Getting Information for breaking
      ansible.builtin.shell: "grep home /etc/passwd | cut -d':' -f6"
      register: home_dirs

    - name: Adding the break
      ansible.builtin.lineinfile:
        path: "{{ item }}/.bashrc"
        line: "{{ proxy_line }}"
        create: true
        state: present
      loop: "{{ home_dirs.stdout_lines | default([]) }}"
      vars:
        proxy_line: |
          export HTTP_PROXY=http://satellite.{{ var_subdomain_internal }}:80
          export HTTPS_PROXY=http://satellite.{{ var_subdomain_internal }}:443
      notify: Source .bashrc

    - name: Breaking the big boss
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "{{ proxy_line }}"
        create: true
        state: present
      vars:
        proxy_line: |
          export HTTP_PROXY=http://satellite.{{ var_subdomain_internal }}:80
          export HTTPS_PROXY=http://satellite.{{ var_subdomain_internal }}:443
      notify: Source .bashrc

  handlers:
    - name: Source .bashrc
      ansible.builtin.shell: source ~/.bashrc
      become: true
