# This needs to be Reviewed. Not sure about what exactly needs to be broken here.

---
- name: Break the connectivity to the Capsule Server
  hosts: capsule
  tasks:
  - name: "backup the certificate relationship with the capsule"
    ansible.builtin.copy:
      remote_src: true
      src: "/etc/foreman/client_cert.pem"
      dest: "/tmp/"
    become: true
   
  - name: "backup the certificate relationship with the capsule"
    ansible.builtin.copy:
    remote_src: true
    src: "/etc/foreman/client_cert.pem"
    dest: "/etc/foreman/client_cert.pem"
  become: true
      
