# Break the Capsule by removing certificates and restarting foreman-proxy service.                     
---                                                                                                    
- name: Break connectivity to the Capsule Server                                                       
  hosts: "capsule.{{ var_subdomain_internal }}"                                                        
  vars_files: /tmp/vars.yml                                                                            
  become: True                                                                                         
  tasks:                                                                                               
  - name: "Take backup of Capsule certificates"                                                        
    ansible.builtin.copy:                                                                              
      remote_src: true                                                                                 
      src: "/etc/foreman-proxy"
      dest: "/tmp/"

  - name: "Remove Capsule certificates"
    ansible.builtin.file: 
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/foreman-proxy/foreman_ssl_cert.pem
      - /etc/foreman-proxy/foreman_ssl_ca.pem
      - /etc/foreman-proxy/foreman_ssl_key.pem

  - name: Restart foreman-proxy service
    ansible.builtin.service:
      name: foreman-proxy
      state: restarted