---
- name: "Break Registration on Node 2"
  vars_files:
    - values.yml
  hosts: "{{ workshop_node2 }}"
  tasks:
  
  - name: "Unregister the node from the Satellite"    
    redhat.rhel_system_roles.redhat_subscription:
      state: absent
    become: true

  - name: "Break rhsm.conf"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      search_string: "proxy_hostname = "
      line: "proxy_hostname = thisproxygoesnowhere.local"


  - name: "Break rhsm.conf part 2"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      search_string: "manage_repos = 1"
      line: "manage_repos = 0"
      
