---                                                                                                    
- name: "Fix Registration on Node 2"                                                                   
  vars_files:                                                                                          
    - /tmp/vars.yml                                                                                    
  hosts: "node2.{{ var_subdomain_internal }}"                                                          
  tasks:
  - name: Getting Information for breaking
    ansible.builtin.shell: "grep home /etc/passwd | cut -d':' -f6"
    register: home_dirs

  - name: Removing the break
    ansible.builtin.shell: "for i in {/home/ec2-user/.bashrc,/root/.bashrc}; do sed -i -e 's|export HTTPS_PROXY=http://satellite.{{ var_subdomain_internal }}:443||g' $i; sed -i -e 's|export HTTP_PROXY=http://satellite.{{ var_subdomain_internal }}:80||g' $i; done; unset HTTPS_PROXY; unset HTTP_PROXY"
    notify: Source .bashrc

  - name: "Unregister the node from the Satellite"
    redhat.rhel_system_roles.redhat_subscription:
      state: absent
    become: true
  
  handlers:
    - name: Source .bashrc
      ansible.builtin.shell: source ~/.bashrc
      become: true

#Register Nodes to the Capsule server
- name: Register all Nodes to Capsule
  become: True
  vars_files:
    - /tmp/vars.yml
  hosts: nodes
  tasks:
  - name: Remove all katello-ca-consumer RPMs
    shell: 'dnf remove katello-ca-consumer-* -y'

  - name: Remove old registration
    shell: 'subscription-manager clean'

#Install katello-ca-consumer RPM on Node Clients
  - name: Install katello-ca-consumer RPM
    shell: 'dnf install http://capsule.{{ var_subdomain_internal }}/pub/katello-ca-consumer-latest.noarch.rpm -y'

#Register Node Clients to the Capsule server to use RHEL9-CV
  - name: Register Nodes to Capsule
    shell: 'subscription-manager register --username {{var_workshop_satellite_user_name}} --password {{var_workshop_satellite_user_password}} --org "Default_Organization" --environments Development/RHEL9-CV --force'

#Enable the BaseOS, Appstream, and Satellite-Client repos on Node1
  - name: Enable BaseOS, Appstream, Satellite-Client repos on Nodes
    shell: 'subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms --enable rhel-9-for-x86_64-baseos-rpms --enable satellite-client-6-for-rhel-9-x86_64-rpms'
