---
- name: "Fix Registration on Node 2"
  vars_files:
    - values.yml
  hosts: "{{ workshop_node2 }}"


  tasks:
  
  - name: "Fix rhsm.conf"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      line: "proxy_hostname = "
      search_string: "proxy_hostname = thisproxygoesnowhere.local"


  - name: "Break rhsm.conf part 2"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      line: "manage_repos = 1"
      search_string: "manage_repos = 0"


  - name: "Unregister the node from the Satellite"
    redhat.rhel_system_roles.redhat_subscription:
      state: absent
    become: true

#Register Nodes to the Capsule server
- name: Register all Nodes to Capsule
  become: True
  vars_files:
    - values.yml
  hosts: nodes
  tasks:
  - name: Remove all katello-ca-consumer RPMs
    shell: 'dnf remove katello-ca-consumer-* -y'

  - name: Remove old registration
    shell: 'subscription-manager clean'

#Install katello-ca-consumer RPM on Node Clients
  - name: Install katello-ca-consumer RPM
    shell: 'dnf install http://capsule.{{ subdomain_internal }}/pub/katello-ca-consumer-latest.noarch.rpm -y'

#Register Node Clients to the Capsule server to use RHEL9-CV
  - name: Register Nodes to Capsule
    shell: 'subscription-manager register --username {{workshop_satellite_user_name}} --password {{workshop_satellite_user_password}} --org "Default_Organization" --environments Development/RHEL9-CV --force'

#Enable the BaseOS, Appstream, and Satellite-Client repos on Node1
  - name: Enable BaseOS, Appstream, Satellite-Client repos on Nodes
    shell: 'subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms --enable rhel-9-for-x86_64-baseos-rpms --enable satellite-client-6-for-rhel-9-x86_64-rpms'
