---
- name: Fix Client Execution For Module 2
  hosts: localhost
  vars_files: /tmp/vars.yml
  tasks:
  - name: Create Subnet for Lab
    redhat.satellite.subnet:
      name: "Lab Subnet"
      description: "Subnet for Satellite Lab"
      network: "192.168.0.0"
      mask: "255.255.255.254"
      gateway: "192.168.0.1"
      boot_mode: "DHCP"
      remote_execution_proxies:
        - "satellite.{{ var_subdomain }}"
        - "capsule.{{ var_subdomain }}"
      mtu: 9001
      domains:
        - "{{ var_subdomain_internal }}"
      organizations:
        - "Default Organization"
      locations:
        - "Default Location"
      username: "{{ var_workshop_satellite_user_name }}"
      password: "{{ var_workshop_satellite_user_password }}"
      server_url: "https://{{ var_workshop_satellite_url }}"
      state: present