---
- name: "Fix Registration on Node 2"
  hosts: node2
  tasks:
  
  - name: "Fix rhsm.conf"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      line: "proxy_hostname = "
      search_string: "proxy_hostname = thisproxygoesnowhere.local"


  - name: "Break rhsm.conf part 2"
    become: true
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      line: "manage_repos = 1"
      search_string: "manage_repos = 0"


  - name: "Unregister the node from the Satellite"
    redhat.rhel_system_roles.redhat_subscription:
      state: absent
    become: true

- hosts: localhost
  tasks: 
  - name: "Generate registration command"
  # note that this module isn't in the Execution Environment and needs to be added.
    redhat.satellite.registration_command:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      validate_certs: false
      smart_proxy: "capsule.{{ subdomain }}"
      setup_remote_execution: true
      organization: "Default Organization"
      activation_keys: "client_key"
      insecure: true
      lifecycle_environment: "Development"        
    register: command
      
- hosts: node2
  tasks:
  - name: "Register the hosts to the capsule"
    ansible.builtin.shell:
      cmd: "{{ command.registration_command }}"